import { useEffect, useState } from 'react'
import { Navigate, useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, CheckCircle2, Eye, Lightbulb } from 'lucide-react'
import { Button, ButtonLink, Card, Spinner } from '../components/ui'
import { lessonById } from '../data/lessons'
import { openLesson, saveLessonProgress } from '../lib/db'
import type { LessonProgress } from '../lib/types'
import { useAuth } from '../store/auth'

export default function Lesson() {
 const { lessonId='' }=useParams(); const lesson=lessonById(lessonId); const navigate=useNavigate(); const [progress,setProgress]=useState<LessonProgress|null>(null); const [shown,setShown]=useState(false)
 useEffect(()=>{if(lesson) void openLesson(lesson.id).then(setProgress)},[lesson?.id])
 if(!lesson)return <Navigate to="/study/learn" replace/>; if(!progress)return <Spinner label="Opening lesson" />
 const setRecall=async(value:'remembered'|'nearly'|'forgot')=>{const next={...progress,recalls:{...progress.recalls,0:value}};setProgress(next);await saveLessonProgress(next);void useAuth.getState().syncUp()}
 const complete=async()=>{const next={...progress,completedAt:Date.now()};setProgress(next);await saveLessonProgress(next);void useAuth.getState().syncUp()}
 return <div className="mx-auto max-w-3xl space-y-5"><Button variant="ghost" className="px-0" onClick={()=>navigate('/study/learn')}><ArrowLeft size={17}/>All lessons</Button><header><p className="eyebrow">{lesson.topic} · {lesson.minutes} minutes</p><h1 className="mt-1 text-2xl font-semibold text-navy sm:text-3xl">{lesson.title}</h1><p className="mt-2 text-muted">{lesson.summary}</p></header><Card><h2 className="font-semibold">Understand it</h2><div className="mt-4 space-y-4">{lesson.facts.map(f=><div key={f.heading}><h3 className="font-medium">{f.heading}</h3><p className="mt-1 text-sm leading-relaxed text-muted">{f.text}</p></div>)}</div></Card><Card className="border-accent/30 bg-brand-soft/40"><h2 className="flex items-center gap-2 font-semibold"><Lightbulb size={19} className="text-accent"/>Remember it</h2><h3 className="mt-3 font-medium">{lesson.memoryAid.title}</h3><p className="mt-1 text-sm leading-relaxed text-muted">{lesson.memoryAid.text}</p><p className="mt-3 text-xs text-muted">This is a memory aid, not an additional test fact.</p></Card><Card><h2 className="font-semibold">Try recalling it</h2><p className="mt-3 font-medium">{lesson.recall.prompt}</p>{shown ? <div className="mt-3 rounded-xl bg-good-soft p-3 text-sm text-good">{lesson.recall.answer}</div> : <Button variant="secondary" className="mt-4" onClick={()=>setShown(true)}><Eye size={16}/>Reveal answer</Button>}{shown&&<div className="mt-4"><p className="text-sm text-muted">How did that feel?</p><div className="mt-2 flex flex-wrap gap-2">{([['remembered','Remembered'],['nearly','Nearly'],['forgot','Forgot']] as const).map(([v,label])=><Button key={v} variant={progress.recalls[0]===v?'primary':'secondary'} onClick={()=>void setRecall(v)}>{label}</Button>)}</div></div>}</Card><Card><h2 className="font-semibold">Practise next</h2><p className="mt-1 text-sm text-muted">Use flashcards or take a practice set to check recall without hints.</p><div className="mt-4 flex flex-wrap gap-2"><ButtonLink to="/study/flashcards" variant="secondary">Open flashcards</ButtonLink><ButtonLink to="/practice" variant="secondary">Practise questions</ButtonLink>{progress.completedAt?<ButtonLink to="/study/learn">Back to lessons</ButtonLink>:<Button onClick={()=>void complete()}><CheckCircle2 size={17}/>Mark lesson complete</Button>}</div></Card></div>
}
